### ISSUE TITLE
For RHEL9, libvirtd service should be disabled and start virt<service-name>d{,-ro,-admin}.socket instead.

### ISSUE THREAD

**Issue by knoha-rh** [openstack-k8s-operators/ci-framework#751]
When ci-framework steup runs on RHEL9 system, virt-install always failed.
It looks that virt-install requires individual virt<service-name>d{,-ro,admin}.socket. However, the related daemons conflicts with libvirt.service.

To avoid this situation, we should add something like below.

- libvirt_manager/tasks/virsh_checks.yml
~~~
- name: Ensure virt realted sockets are started and enabled
  become: true
  when: ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_major_version == '9'
  block:
    - name: Ensure virt<<service name>>d.socket are started and enbled
      ansible.builtin.service:
        name: "virt{{ item }}d.socket"
        state: started
        enabled: true
      loop:
        - qemu
        - network
        - nodedev
        - nwfilter
        - secret
        - storage
        - interface
    - name: Ensure virt<<service name>>d-ro.socket are started and enbled
      ansible.builtin.service:
        name: "virt{{ item }}d-ro.socket"
        state: started
        enabled: true
      loop:
        - qemu
        - network
        - nodedev
        - nwfilter
        - secret
        - storage
        - interface
    - name: Ensure virt<<service name>>d-admin.socket are started and enbled
      ansible.builtin.service:
        name: "virt{{ item }}d-admin.socket"
        state: started
        enabled: true
      loop:
        - qemu
        - network
        - nodedev
        - nwfilter
        - secret
        - storage
        - interface

- name: Enable libvirt and configure  virtproxyd service
  when: "ansible_distribution in ['CentOS', 'RedHat'] and ansible_distribution_major_version == '8'"
  become: true
  ansible.builtin.service:
    name: "{{ cifmw_libvirt_manager_daemon }}"
    state: started
    enabled: true
~~~

**Comment by cjeanner** [comment]
Unfortunately this isn't possible: it seems dev-scripts on its own is (re)starting the libvirtd.service. The only way to get out of that hell of socket was to remove the timeout set on the virtproxyd.service, allowing it to be long-running. If dev-scripts on its own and the underlying metal3-dev-env could NOT manage libvirtd service, it may be possible... But there's no option to disable that (wrong) management :(.

**Comment by knoha-rh** [comment]
Hi Cedric,

Thank you for your comment. I ran ci-framework on RHEL9.2. It looks that modular libvirt and monolithic libvirt conflicts in the installation. I disables all monolithic lilbvirt sockets then the installation runs well until 'edpm_deploy : Wait for OpenStackDataPlaneNodeSet to be deployed' Do you expect RHEL9.2 is out of scope as hypervisor with ci-framework?

**Comment by cjeanner** [comment]
Hello Keigo,

el-9.2 hypervisor is definitively in the scope - older releases not so much actually. I just nudged a patch holding your proposal with some tweaks, it should then match the modular vs monolithic libvirt properly. EL-8 isn't supported officially, but I kept the check "just to be sure" - it doesn't really cost much at this point.
